[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "pythonsdk"
requires-python = ">=3.8"
dependencies = ["cffi"]
dev-dependencies = ["pytest"]

[tool.maturin]
bindings = "cffi"